version: '3'
services:
  webapp:
    image: chourmovs/blissify-webapp:latest  # Utilise ton image pré-construite
    volumes:
      - ./webapp:/usr/src/app  # Monte ton dossier de développement local dans le conteneur
      - /usr/src/app/node_modules  # Evite de monter les node_modules locales
    ports:
      - "3000:3000"  # Expose le port de ton application Node.js
    environment:
      NODE_ENV: development  # En mode développement
    command: npm run dev  # Démarre ton application en mode dev (nodemon)

