name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Déclenche le workflow sur les push vers la branche principale
  schedule:
    - cron: '0 0 * * 1'  # Déclenche le workflow chaque lundi à minuit UTC
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Clean up existing webapp directory
      run: |
        if [ -d ./webapp ]; then
        rm -rf ./webapp
        fi

    - name: Clone webapp repository
      run: |
        git clone https://${{ secrets.GH_PAT }}@github.com/chourmovs/webapp.git ./webapp

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: chourmovs/blissify-webapp:latest
        cache-from: type=registry,ref=chourmovs/blissify-webapp:cache
        cache-to: type=registry,ref=chourmovs/blissify-webapp:cache,mode=max

    - name: Image details
      run: docker images
